config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users
  namespace :admin do
    resources :users
    resources :questions
    resources :subjects do
      # get 'questions',on: :member
    end
    resources :exams
  end
  get :admin, to: 'admin/subjects#index'

  resources :exam_submissions, only: [ :new, :create ]
  # resources :exam_submission_answers, only: [ :create ]
end

app/models/admin/subject.rb
# frozen_string_literal: true

module Admin
  # Subject.rb
  class Subject < ApplicationRecord
    self.table_name = 'subjects'

    has_many :questions, dependent: :destroy
    has_and_belongs_to_many :exams

    validate :validate_number_of_questions
    
    private

    def validate_number_of_questions
      if self.num_of_questions == self.questions.size
        errors.add(:num_of_questions, 'limit exceeded please either remove questions or increase limit.')
      end
    end
  end
end

app/controllers/admin/subjects_controller.rb
# frozen_string_literal: true

module Admin
  # SubjectsController
  class SubjectsController < Admin::ApplicationController
    before_action :set_admin_subject, only: %i[show edit update destroy]

    # GET /admin/subjects or /admin/subjects.json
    def index
      @admin_subjects = Admin::Subject.all
    end

    # GET /admin/subjects/1 or /admin/subjects/1.json
    def show
      @admin_questions = @admin_subject.questions
    end

    # GET /admin/subjects/new
    def new
      @admin_subject = Admin::Subject.new
    end

    # GET /admin/subjects/1/edit
    def edit; end

    # def questions
    #   @subject = Subject.find(params[:id])
    #   render json: { questions: @subject.questions } 
    # end

    # POST /admin/subjects or /admin/subjects.json
    def create
      @admin_subject = Admin::Subject.new(admin_subject_params)

      respond_to do |format|
        if @admin_subject.save
          format.html { redirect_to admin_subject_url(@admin_subject), notice: 'Subject was successfully created.' }
          format.json { render :show, status: :created, location: @admin_subject }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @admin_subject.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/subjects/1 or /admin/subjects/1.json
    def update
      respond_to do |format|
        if @admin_subject.update(admin_subject_params)
          format.html { redirect_to admin_subject_url(@admin_subject), notice: 'Subject was successfully updated.' }
          format.json { render :show, status: :ok, location: @admin_subject }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @admin_subject.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/subjects/1 or /admin/subjects/1.json
    def destroy
      @admin_subject.destroy

      respond_to do |format|
        format.html { redirect_to admin_subjects_url, notice: 'Subject was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_subject
      @admin_subject = Admin::Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_subject_params
      params.require(:admin_subject).permit(:name, :num_of_questions)
    end
  end
end

app/helpers/admin/subjects_helper.rb
# frozen_string_literal: true

module Admin
  # SubjectsHelper
  module SubjectsHelper
    def all_subjects
      Admin::Subject.all.map { |subject| [subject.name, subject.id] }
    end
  end
end

app/views/admin/subjects/_form.html.erb
<%= form_with(model: admin_subject, html: {class: 'mx-auto', style: 'max-width: 450px;'}) do |form| %>
  <% if admin_subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_subject.errors.count, "error") %> prohibited this admin_subject from being saved:</h2>

      <ul>
        <% admin_subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group row'>
    <%= form.label :name, 'Name: ', class: 'col-2' %>
    <div class='col-10'>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group row'>
    <%= form.label :num_of_questions,'Num of questions: ', class: 'col-2' %>
    <div class='col-10'>
      <%= form.number_field :num_of_questions, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <%= form.submit 'Submit',class:'btn btn-primary col-12' %>
  </div>
<% end %>

app/views/admin/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
  <%= link_to subject do %>
    <strong><%= subject.name %></strong>
  <% end %>

  <p>
    <strong>Num of questions:</strong>
    <%= subject.num_of_questions %>
  </p>

</div>

app/views/admin/subjects/_subject_questions.html.erb
<strong>Num Of Questions: <%= questions.size %></strong>
<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Input Type</th>
      <th>Options</th>
      <th>Answer</th>
      <th></th>
    </tr>
  </thead>
  <% questions.each do |question| %>
    <tbody>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.inputType %></td>
        <td><%= question.optionValues.values %></td>
        <td><%= link_to 'show',question, class: 'btn btn-primary' %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/admin/subjects/edit.html.erb
<div class="text-center mb-5">
  <h1>Editing Subject: </h1>
</div>

<%= render "form", admin_subject: @admin_subject %>

<br>

<div class="text-center">
  <%= link_to "Show", @admin_subject %> |
  <%= link_to "Back", admin_subjects_path %>
</div>

app/views/admin/subjects/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between">
  <div>
    <h1>Subjects</h1>
  </div>
  <div>
    <h1><%= link_to "New", new_admin_subject_path, class: 'btn btn-primary' %></h1>
  </div>
</div>
<div id="admin_subjects">
  <div class='row'>
    <% @admin_subjects.each do |admin_subject| %>
      <div class='col-3 card mx-2 my-2'>
        <%= render admin_subject %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/subjects/new.html.erb
<div class="text-center mb-5">
  <h1>New Subject: </h1>
</div>

<%= render "form", admin_subject: @admin_subject %>

<br>

<div class="text-center">
  <%= link_to "Back", admin_subjects_path %>
</div>

app/views/admin/subjects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render 'subject_questions',questions: @admin_questions %>

<div class="d-flex">
  <%= link_to "Edit", edit_admin_subject_path(@admin_subject), class: 'btn btn-link' %>
  <%= link_to "Back", admin_subjects_path, class: 'btn btn-link' %>
  <%= link_to "Add Question", new_admin_question_path, class: 'btn btn-link' %>
  <%= button_to "Destroy", @admin_subject, method: :delete, class: 'btn btn-link py-2 px-3', id: 'button_css' %>
</div>