config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users
  namespace :admin do
    resources :users
    resources :questions
    resources :subjects do
      # get 'questions',on: :member
    end
    resources :exams
  end
  get :admin, to: 'admin/subjects#index'

  resources :exam_submissions, only: [ :new, :create ]
  # resources :exam_submission_answers, only: [ :create ]
end

app/models/admin/exam.rb
module Admin
  class Exam < ApplicationRecord
    self.table_name = 'exams'

    has_and_belongs_to_many :subjects
    has_many :users
    has_many :exam_submissions, dependent: :destroy
    
    validates :name, presence: true, uniqueness: true
    validate :should_have_one_subject

    def subject_names
      subjects.joins(:questions).distinct.pluck(:name).join(', ')
    end

    private
    
    def should_have_one_subject
      if self.subject_ids.blank?
        errors.add(:subject_ids, 'can`t be blank.')
      end
    end
    
  end
end

app/controllers/admin/exams_controller.rb
# frozen_string_literal: true

module Admin
  # examsController
  class ExamsController < Admin::ApplicationController
    before_action :set_admin_exam, only: %i[show edit update destroy]

    def index
      @admin_exams = Admin::Exam.all
    end

    def show
      @questions = Admin::Question.joins(subject: :exams).where(exams: {id: params[:id]}).order(:id)
    end

    def new
      @admin_exam = Admin::Exam.new
    end

    def edit; end

    def create
      @admin_exam = Admin::Exam.new(admin_exam_params)

      respond_to do |format|
        if @admin_exam.save
          format.html { redirect_to admin_exam_url(@admin_exam), notice: 'exam was successfully created.' }
          format.json { render :show, status: :created, location: @admin_exam }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @admin_exam.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @admin_exam.update(admin_exam_params)
          format.html { redirect_to admin_exam_url(@admin_exam), notice: 'Exam was successfully updated.' }
          format.json { render :show, status: :ok, location: @admin_exam }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @admin_exam.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @admin_exam.destroy

      respond_to do |format|
        format.html { redirect_to admin_exams_url, notice: 'Exam was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_admin_exam
      @admin_exam = Admin::Exam.find(params[:id])
    end

    def admin_exam_params
      params.require(:admin_exam).permit(:name, subject_ids: [])
    end
  end
end

app/helpers/admin/exams_helper.rb
# frozen_string_literal: true

module Admin
  # QuestionsHelper
  module ExamsHelper
    # def subject_names
    #   @subjects.map {|subject| [subject.name,subject.id]}
    # end
  end
end

app/views/admin/exams/_exam.html.erb
<div class="card col-3 mx-3 my-2">
  <%= link_to exam do %>
    <p>
      <%= exam.name %>
    </p>
  <% end %>
</div>

app/views/admin/exams/_exam_questions_form.html.erb
<h1>hi</h1>

app/views/admin/exams/_form.html.erb
<%= form_with(model: admin_exam, html: {class: 'mx-auto mb-4', style: 'max-width: 450px;'}) do |form| %>
  <% if admin_exam.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_exam.errors.count, "error") %> prohibited this Exam from being saved:</h2>

      <ul>
        <% admin_exam.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group row'>
    <%= form.label :name, 'Name: ', class: 'col-2' %>
    <div class='col-10'>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class='form-group row'>
    <%= form.label :subjects,'Subjects: ', class: 'col-2' %>
    <div class='col-10'>
      <%= form.collection_check_boxes :subject_ids, Admin::Subject.all, :id, :name, {hide_label: true } %>
    </div>
  </div>
  <div class='row'>
    <%= form.submit class:'btn btn-primary col-12' %>
  </div>
<% end %>

app/views/admin/exams/edit.html.erb
<div class='text-center mb-5'>
  <h1>Editing Exam:</h1>
</div>

<%= render "form", admin_exam: @admin_exam %>

<div class='text-center'>
  <%= link_to "Show this exam", @admin_exam %> |
  <%= link_to "Back to exams", admin_exams_path %>
</div>

app/views/admin/exams/index.html.erb
<div class='row'>
	<% @admin_exams.each do |admin_exam| %>
	  <%= render admin_exam %>
	<% end %>
</div>
<%= link_to 'New', new_admin_exam_path, class: 'btn btn-primary' %>

app/views/admin/exams/new.html.erb
<div class='text-center mb-5'>
  <h1>New Exam: </h1>
</div>

<%= render "form", admin_exam: @admin_exam %>

<br>

<div class='text-center'>
  <%= link_to "Back", admin_exams_path %>
</div>

app/views/admin/exams/show.html.erb
<div class='container'>
  <div class="h3 d-flex justify-content-center">
     Exam: <%= @admin_exam.name %>
  </div>
  <div class="h4 d-flex justify-content-center">
     Subjects: <%= @admin_exam.subject_names %>
  </div>
</div>
<% quesiton_no = 0 %>
<% @questions.each do |question| %>
	<div class="col-7 mt-3">
    <div class="card">
      <div class="card-body">
      	<% quesiton_no += 1 %>
        <p class="card-text"><span class='h5'><%= quesiton_no.to_s + ': ' %></span><%= question.title %></p>
        <% if question.inputType == 'list' || question.inputType == 'true/false' %>
        	<% question.optionValues.values.each do |option| %>
        		<div class="form-check">
		          <input class="form-check-input" type="radio" name="<%= question.id %>" id="<%= question.id %>" value="<%= question.id %>">
		          <label class="form-check-label" for="option1">
		            <%= option %>
		          </label>
		        </div>
        	<% end %>
        <% elsif question.inputType == 'multipleChoice' %>
        	<% question.optionValues.values.each do |option| %>
        		<div class="form-check">
		          <input class="form-check-input" type="checkbox" name="<%= question.id %>" id="<%= question.id %>" value="<%= question.id %>">
		          <label class="form-check-label" for="option1">
		            <%= option %>
		          </label>
		        </div>
        	<% end %>
        <% end %>
      </div>
    </div>
 	</div>
<% end %>

<div class="d-flex">
	<%= link_to "Back", admin_exams_path, class: 'btn btn-md btn-link' %>
	<%= link_to "Edit", edit_admin_exam_path(@admin_exam), class: 'btn btn-md btn-link' %>
	<%= button_to 'Delete', @admin_exam, method: :delete, class: 'btn btn-md btn-link' %>
</div>