config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users
  namespace :admin do
    resources :users
    resources :questions
    resources :subjects do
      # get 'questions',on: :member
    end
    resources :exams
  end
  get :admin, to: 'admin/subjects#index'

  resources :exam_submissions, only: [ :new, :create ]
  # resources :exam_submission_answers, only: [ :create ]
end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class='container'>
    <%= link_to 'Home',admin_path,class: 'navbar-brand' %>
    <div class="collapse navbar-collapse row" id="navbarNav">
      <ul class="navbar-nav col-11">
        <li class="nav-item active">
          <%= link_to 'Subject',admin_subjects_path,class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Questions',admin_questions_path,class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Exams',admin_exams_path,class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users',admin_users_path,class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav mt-3 col-1">
        <%= button_to 'Logout',destroy_user_session_path,method: :delete, data: { :no_turbolink => true }, class: 'btn btn-danger nav-link' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleQuizNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <style type="text/css">
      #button_css{
        margin: 0px;
        padding: 0px;
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/admin/header' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>