config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users
  namespace :admin do
    resources :users
    resources :questions
    resources :subjects do
      # get 'questions',on: :member
    end
    resources :exams
  end
  get :admin, to: 'admin/subjects#index'

  resources :exam_submissions, only: [ :new, :create ]
  # resources :exam_submission_answers, only: [ :create ]
end

app/models/admin/question.rb
# frozen_string_literal: true

module Admin
  # Question.rb
  class Question < ApplicationRecord
    self.table_name = 'questions'

    enum :inputType, ['true/false', 'multipleChoice', 'list', 'descriptive']
    store :optionValues, accessors: %i[option1 option2 option3 option4], coder: JSON

    belongs_to :subject

    validates_presence_of :inputType, :title, allow_blank: false
    validates_associated :subject

    validate :validate_option_values
    
    private

    def validate_option_values
      if ( inputType == 'multipleChoice' || inputType == 'list' ) && ( option1.blank? || option2.blank? || option3.blank? || option4.blank? )
        errors.add(:options, 'must be fullfilled.')
      end
    end

  end
end















# validate :validate_true_and_false
    # validate :validate_multiple_choice
    # validate :validate_list
    
    # def validate_true_and_false
    #   if inputType == 'true/false' && !answer.present?
    #     errors.add(:answer, ' should be present')
    #   end
    # end

    # def validate_multiple_choice
    #   if (inputType == 'multipleChoice')
    #     unless (optionValues.keys.size == 4)
    #       errors.add(:all, 'options should be fill')
    #     end
    #     unless optionValues.values.include?('1')
    #       errors.add(:one, 'answer must be true')
    #     end
    #   end
    # end

    # def validate_list
    #   if (inputType == 'list') && !(optionValues.keys.size == 4 && optionValues.values.include?(true))
    #     errors.add(:option, 'field should be filled properly')
    #   end
    # end

    # def answer
    #   if inputType == 'true/false'
    #     read_attribute(:answer)
    #   elsif inputType == 'multipleChoice'
    #     optionValues.select {|key,value| value == '1'}.keys
    #   elsif inputType == 'list'
    #     optionValues.select { |key,value| value == true }.keys.first
    #   else
    #     '..........'
    #   end
    # end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

module Admin
  # QuestionsController
  class QuestionsController < Admin::ApplicationController
    before_action :set_admin_question, only: %i[show edit update destroy]

    # GET /admin/questions or /admin/questions.json
    def index
      @admin_questions = Admin::Question.all
    end

    # GET /admin/questions/1 or /admin/questions/1.json
    def show; end

    # GET /admin/questions/new
    def new
      @admin_question = Admin::Question.new
    end

    # GET /admin/questions/1/edit
    def edit; end

    # POST /admin/questions or /admin/questions.json
    def create
      optionValues = params[:optionsKeys]
      @admin_question = Admin::Question.new(admin_question_params)

      respond_to do |format|
        if @admin_question.save
          format.html { redirect_to admin_question_url(@admin_question), notice: 'Question was successfully created.' }
          format.json { render :show, status: :created, location: @admin_question }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @admin_question.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/questions/1 or /admin/questions/1.json
    def update
      respond_to do |format|
        if @admin_question.update(admin_question_params)
          format.html { redirect_to admin_question_url(@admin_question), notice: 'Question was successfully updated.' }
          format.json { render :show, status: :ok, location: @admin_question }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @admin_question.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/questions/1 or /admin/questions/1.json
    def destroy
      @admin_question.destroy

      respond_to do |format|
        format.html { redirect_to admin_questions_url, notice: 'Question was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_question
      @admin_question = Admin::Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_question_params
      case params[:admin_question][:inputType]
      when 'true/false'
        params.require(:admin_question).permit(:title, :inputType,
                                               :subject_id).with_defaults(option1: true, option2: false)
      when 'multipleChoice'
        params.require(:admin_question).permit(:title, :inputType,:subject_id, :option1, :option2, :option3, :option4)
      when 'list'
        params.require(:admin_question).permit(:title, :inputType,:subject_id, :option1, :option2, :option3, :option4)
      else
        params.require(:admin_question).permit(:title, :inputType, :subject_id)
      end
    end


  end
end

app/helpers/admin/questions_helper.rb
# frozen_string_literal: true

module Admin
  # QuestionsHelper
  module QuestionsHelper
    def input_type_options
      Admin::Question.inputTypes.keys
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with(model: admin_question, html: {class: 'mx-auto', style: 'max-width: 450px;'}) do |form| %>
  <% if admin_question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% admin_question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row form-label-group mb-4'>
    <%= form.label :title, 'Title: ',class: 'col-2' %>
    <div class='col-10'>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class='row form-label-group mb-4'>
    <%= form.label :inputType, 'Input Type: ',class: 'col-2' %>
    <div class='col-10'>
      <%= form.select :inputType, input_type_options, {}, :include_blank => 'Select Question Type', class: 'form-control' %>
    </div>
  </div>

  <div class='hidden' id='optionBlock'>
    <div class='form-group mb-3 row'>
      <%= form.label :option1, 'option1: ',class: 'col-2' %>
      <div class='col-10'>
        <%= form.text_field :option1, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group mb-3 row'>
      <%= form.label :option2, 'option2: ',class: 'col-2' %>
      <div class='col-10'>
        <%= form.text_field :option2, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group mb-3 row'>
      <%= form.label :option3, 'option3: ',class: 'col-2' %>
      <div class='col-10'>
        <%= form.text_field :option3, class: 'form-control' %>
      </div>
    </div>

    <div class='form-group mb-3 row'>
      <%= form.label :option4, 'option4: ',class: 'col-2' %>
      <div class='col-10'>
        <%= form.text_field :option4, class: 'form-control' %>
      </div>
    </div>
  </div>

  
  <div class='form-group mb-3 row'>
    <%= form.label :subject_id,'SubjectId: ',class: 'col-2' %>
    <div class='col-10'>
      <%= form.select :subject_id, all_subjects, {}, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group mt-5 row'>
    <div class='col-12'>
      <%= form.submit 'Submit',class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
var place = {
  "true/false" : "true/false",
  "multipleChoice": "select from option",
  "list": "select from option"
}
  function fieldCondition(inputType){
    $('#admin_question_answer').attr("placeholder", place[inputType]);
    let removeClassHidden = (id) => $(`#${id}`).removeClass("hidden");
    let addClassHidden = (id) => $(`#${id}`).addClass("hidden");

    if (inputType === 'multipleChoice' || inputType === 'list'){
      removeClassHidden('optionBlock');
    }
    else{
      addClassHidden('optionBlock');
    }
  }
  var setField = function() {
    const inputType = $(this).val();
    fieldCondition(inputType)
  }
  $( document ).ready(function() {
    const inputType = $('#admin_question_inputType')[0].value;
    fieldCondition(inputType);
  });
  $('#admin_question_inputType').change(setField);
</script>

app/views/admin/questions/_question.html.erb
<div class='card col-5 mx-4 my-4' id="<%= dom_id question %>">
  <div class="mx-3">
    <p>
      <strong>Title:</strong>
      <%= question.title %>
    </p>

    <p>
      <strong>InputType:</strong>
      <%= question.inputType %>
    </p>

    <p>
      <strong>Optionvalues:</strong>
      <%= question.optionValues.values %>
    </p>

    <p>
      <strong>Subject:</strong>
      <%= question.subject.name %>
    </p>

  </div>

  <div class='d-flex'>
    <%= link_to "Edit", edit_admin_question_path(question), class: 'btn btn-link' %>
    <%= link_to "Back", :back, class: 'btn btn-link' %>
    <%= button_to "Destroy", question, method: :delete, class: 'btn btn-link' %>
  </div>

</div>

app/views/admin/questions/edit.html.erb
<div class="text-center mb-5">
  <h1 class="h3 mb-3 font-weight-normal">Revise Your Question: </h1>
</div>
<%= render "form", admin_question: @admin_question %>

<div class='text-center'>
  <%= link_to "Show", @admin_question %> |
  <%= link_to "Back", admin_questions_path %>
</div>

app/views/admin/questions/index.html.erb
<p style="color: green"><%= notice %></p>
<div class='row'>
  <div class="h2 col-10">Questions</div>
  <div class='col-2'>
    <%= link_to "New", new_admin_question_path, class: 'btn btn-primary' %>
  </div>  
</div>
<div id="admin_questions">
  <div class='row'>
    <% @admin_questions.each do |admin_question| %>
      <%= render admin_question %>
    <% end %>
  </div>
</div>

app/views/admin/questions/new.html.erb
<div class='text-center mb-5'>
  <h1>New question: </h1>
</div>

<%= render "form", admin_question: @admin_question %>

<br>

<div class='text-center'>
  <%= link_to "Back", admin_questions_path %>
</div>

app/views/admin/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_question %>